#### Datos deporte

In [2]:
# limpieza y librerías

rm(list = ls())

# Paquetes
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, srvyr, openxlsx, readr, janitor)

Cargando paquete requerido: pacman

In [3]:
url_zip <- "https://www.inegi.org.mx/contenidos/programas/enut/2024/microdatos/enut_2024_bd_csv.zip"

In [5]:
# Crear un directorio temporal para guardar el ZIP
temp_dir <- tempdir()
zip_path <- file.path(temp_dir, "archivo.zip")

In [6]:
# Descargar el ZIP
download.file(url_zip, destfile = zip_path, mode = "wb")

# Descomprimir los archivos dentro del ZIP al mismo directorio temporal
unzip(zip_path, exdir = temp_dir)

# Ver qué archivos se extrajeron
list.files(temp_dir)

[1] "archivo.zip"        "enut_2024_cat.xlsx" "Rf266411d5b1f"
[4] "thogar.csv"         "tmodulo.csv"        "tsdem.csv"
[7] "tvar_crea.csv"      "tvivienda.csv"

In [7]:
# Localizar el CSV (ajusta el nombre según el archivo que haya dentro)
csv_file <- list.files(temp_dir, pattern = "tmodulo.csv", full.names = TRUE)[1]   #Aquí solo se modifica el nombre del archivo,
#dependiendo del que quiera :)

# Leer el CSV
datos <- read_csv(csv_file)

Rows: 74053 Columns: 694
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (532): LLAVEMOD, LLAVEVIV, LLAVEHOG, P4_1C, NIV, P5_8_1_1, P5_8_1_2, P5_...
dbl (162): SEXO, EDAD_V, P4_1, GRA, P4_3, P4_4, P4_5, P4_6, P4_7, P5_1, P5_2...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [8]:
head(datos)

  LLAVEMOD     LLAVEVIV  LLAVEHOG   SEXO EDAD_V P4_1 P4_1C NIV GRA P4_3 ⋯
1 010009401101 010009401 0100094011 2    59     2    NA    03  3   NA   ⋯
2 010009401102 010009401 0100094011 2    33     2    NA    06  2   NA   ⋯
3 010009401103 010009401 0100094011 1    25     2    NA    06  3   NA   ⋯
4 010009402101 010009402 0100094021 1    41     2    NA    06  3   NA   ⋯
5 010009402102 010009402 0100094021 2    42     2    NA    08  4   NA   ⋯
6 010009402103 010009402 0100094021 1    70     2    NA    03  2   NA   ⋯
  CVE_ENT TLOC MENOR10 EST_DIS UPM_DIS FAC_PER CONTROL VIV_SEL HOGAR N_REN
1 01      1    2       0001    00001   518     0100094 01      1     01
2 01      1    2       0001    00001   524     0100094 01      1     02
3 01      1    2       0001    00001   536     0100094 01      1     03
4 01      1    2       0001    00001   541     0100094 02      1     01
5 01      1    2       0001    00001   523     0100094 02      1     02
6 01      1    2       0001    00001   524     0100094 02      1     03

#### Variables que se rescatarán de la base "t_modulo" 

cve_ent: Clave de la entidad


sexo: sexo de la persona


p6_18: Durante la semana pasada, en su tiempo libre ¿usted hizo deporte o ejercicio físico? (fútbol, basquetbol, natación, box, karate, caminar, correr, patinar, andar en bicicleta, yoga, zumba)


p6_18a_1: ¿Cuánto tiempo le dedicó de lunes a viernes? - Horas (lunes-viernes)


p6_18a_2: ¿Cuánto tiempo le dedicó de lunes a viernes? - Minutos (lunes-viernes)


p6_18a_3: ¿Cuánto tiempo le dedicó de lunes a viernes? - Horas (sábado)


p6_18a_4: ¿Cuánto tiempo le dedicó de lunes a viernes? - Minutos (domingo)


variables diseño muestral: est_dis, upm_dis, fac_per

In [9]:
names(datos)

  [1] "LLAVEMOD"     "LLAVEVIV"     "LLAVEHOG"     "SEXO"         "EDAD_V"
  [6] "P4_1"         "P4_1C"        "NIV"          "GRA"          "P4_3"
 [11] "P4_4"         "P4_5"         "P4_6"         "P4_7"         "P5_1"
 [16] "P5_2"         "P5_3C"        "P5_5"         "P5_6_1"       "P5_6_2"
 [21] "P5_6_3"       "P5_6_4"       "P5_6_5"       "P5_6_6"       "P5_6_7"
 [26] "P5_6_8"       "P5_7"         "P5_8_1_1"     "P5_8_1_2"     "P5_8_1_3"
 [31] "P5_8_1_4"     "P5_8_2_1"     "P5_8_2_2"     "P5_8_2_3"     "P5_8_2_4"
 [36] "P5_9_1"       "P5_9_2"       "P5_9_3"       "P5_9_4"       "P5_10"
 [41] "P5_10A"       "P5_11"        "P5_12_1"      "P5_12_2"      "P5_12_3"
 [46] "P5_12_4"      "P6_1_1_1"     "P6_1_1_2"     "P6_1_1_3"     "P6_1_1_4"
 [51] "P6_1_2_1"     "P6_1_2_2"     "P6_1_2_3"     "P6_1_2_4"     "P6_1_3_1"
 [56] "P6_1_3_2"     "P6_1_3_3"     "P6_1_3_4"     "P6_2_1"       "P6_2_1A"
 [61] "P6_2A_1_1_1"  "P6_2A_1_1_2"  "P6_2A_1_1_3"  "P6_2A_1_1_4"  "P6_2A_1_2_1"
 [66] "P6_2A_1_2_2"  "P6_2A_1_2_3"  "P6_2A_1_2_4"  "P6_2_2"       "P6_2A_2_1"
 [71] "P6_2A_2_2"    "P6_2A_2_3"    "P6_2A_2_4"    "P6_2_3"       "P6_2A_3_1"
 [76] "P6_2A_3_2"    "P6_2A_3_3"    "P6_2A_3_4"    "P6_3_1"       "P6_3A_1_1"
 [81] "P6_3A_1_2"    "P6_3A_1_3"    "P6_3A_1_4"    "P6_3_2"       "P6_3A_2_1"
 [86] "P6_3A_2_2"    "P6_3A_2_3"    "P6_3A_2_4"    "P6_3_3"       "P6_3A_3_1"
 [91] "P6_3A_3_2"    "P6_3A_3_3"    "P6_3A_3_4"    "P6_3_4"       "P6_3A_4_1"
 [96] "P6_3A_4_2"    "P6_3A_4_3"    "P6_3A_4_4"    "P6_3_5"       "P6_3A_5_1"
[101] "P6_3A_5_2"    "P6_3A_5_3"    "P6_3A_5_4"    "P6_3_6"       "P6_3A_6_1"
[106] "P6_3A_6_2"    "P6_3A_6_3"    "P6_3A_6_4"    "P6_3_7"       "P6_3A_7_1"
[111] "P6_3A_7_2"    "P6_3A_7_3"    "P6_3A_7_4"    "P6_3_8"       "P6_3A_8_1"
[116] "P6_3A_8_2"    "P6_3A_8_3"    "P6_3A_8_4"    "P6_3_9"       "P6_3A_9_1"
[121] "P6_3A_9_2"    "P6_3A_9_3"    "P6_3A_9_4"    "P6_4_1"       "P6_4A_1_1"
[126] "P6_4A_1_2"    "P6_4A_1_3"    "P6_4A_1_4"    "P6_4_2"       "P6_4A_2_1"
[131] "P6_4A_2_2"    "P6_4A_2_3"    "P6_4A_2_4"    "P6_4_3"       "P6_4A_3_1"
[136] "P6_4A_3_2"    "P6_4A_3_3"    "P6_4A_3_4"    "P6_4_4"       "P6_4A_4_1"
[141] "P6_4A_4_2"    "P6_4A_4_3"    "P6_4A_4_4"    "P6_4_5"       "P6_4A_5_1"
[146] "P6_4A_5_2"    "P6_4A_5_3"    "P6_4A_5_4"    "P6_5_1"       "P6_5A_1_1"
[151] "P6_5A_1_2"    "P6_5A_1_3"    "P6_5A_1_4"    "P6_5_2"       "P6_5A_2_1"
[156] "P6_5A_2_2"    "P6_5A_2_3"    "P6_5A_2_4"    "P6_5_3"       "P6_5A_3_1"
[161] "P6_5A_3_2"    "P6_5A_3_3"    "P6_5A_3_4"    "P6_5_4"       "P6_5A_4_1"
[166] "P6_5A_4_2"    "P6_5A_4_3"    "P6_5A_4_4"    "P6_5_5"       "P6_5A_5_1"
[171] "P6_5A_5_2"    "P6_5A_5_3"    "P6_5A_5_4"    "P6_6_1"       "P6_6A_1_1"
[176] "P6_6A_1_2"    "P6_6A_1_3"    "P6_6A_1_4"    "P6_6_2"       "P6_6A_2_1"
[181] "P6_6A_2_2"    "P6_6A_2_3"    "P6_6A_2_4"    "P6_6_3"       "P6_6A_3_1"
[186] "P6_6A_3_2"    "P6_6A_3_3"    "P6_6A_3_4"    "P6_6_4"       "P6_6A_4_1"
[191] "P6_6A_4_2"    "P6_6A_4_3"    "P6_6A_4_4"    "P6_6_5"       "P6_6A_5_1"
[196] "P6_6A_5_2"    "P6_6A_5_3"    "P6_6A_5_4"    "P6_7_1"       "P6_7A_1_1"
[201] "P6_7A_1_2"    "P6_7A_1_3"    "P6_7A_1_4"    "P6_7_2"       "P6_7A_2_1"
[206] "P6_7A_2_2"    "P6_7A_2_3"    "P6_7A_2_4"    "P6_7_3"       "P6_7A_3_1"
[211] "P6_7A_3_2"    "P6_7A_3_3"    "P6_7A_3_4"    "P6_7_4"       "P6_7A_4_1"
[216] "P6_7A_4_2"    "P6_7A_4_3"    "P6_7A_4_4"    "P6_8_1"       "P6_8A_1_1"
[221] "P6_8A_1_2"    "P6_8A_1_3"    "P6_8A_1_4"    "P6_8_2"       "P6_8A_2_1"
[226] "P6_8A_2_2"    "P6_8A_2_3"    "P6_8A_2_4"    "P6_8_3"       "P6_8A_3_1"
[231] "P6_8A_3_2"    "P6_8A_3_3"    "P6_8A_3_4"    "P6_9_1"       "P6_9A_1_1"
[236] "P6_9A_1_2"    "P6_9A_1_3"    "P6_9A_1_4"    "P6_9_2"       "P6_9A_2_1"
[241] "P6_9A_2_2"    "P6_9A_2_3"    "P6_9A_2_4"    "P6_9_3"       "P6_9A_3_1"
[246] "P6_9A_3_2"    "P6_9A_3_3"    "P6_9A_3_4"    "P6_10_1"      "P6_10A_1_1"
[251] "P6_10A_1_2"   "P6_10A_1_3"   "P6_10A_1_4"   "P6_10_2"      "P6_10A_2_1"
[256] "P6_10A_2_2"   "P6_10A_2_3"   "P6_10A_2_4"   "P6_10_3"      "P6_10A_3_1"
[261] "P6_10A_3_2"   "P6_10A_3_3"   "P6_10A_3_4"   "P6_10_4"      "P6_10A_4_1"
[266] "P6_10A_4_2"   "P6_10A_4_3"   "P6_10A_4_4"   "P6_10_5"      "P6_10A_5_1"
[271] "P6_10A_5_2"   "P6_10A_5_3"   "P6_10A_5_4"   "P6_10_6"      "P6_10A_6_1"
[276] "P6_10A_6_2"   "P6_10A_6_3"   "P6_10A_6_4"   "P6_10_7"      "P6_10A_7_1"
[281] "P6_10A_7_2"   "P6_10A_7_3"   "P6_10A_7_4"   "FILTRO_S6_11" "P6_11_01"
[286] "P6_11A_01_1"  "P6_11A_01_2"  "P6_11A_01_3"  "P6_11A_01_4"  "P6_11_02"
[291] "P6_11A_02_1"  "P6_11A_02_2"  "P6_11A_02_3"  "P6_11A_02_4"  "P6_11_03"
[296] "P6_11A_03_1"  "P6_11A_03_2"  "P6_11A_03_3"  "P6_11A_03_4"  "P6_11_04"
[301] "P6_11A_04_1"  "P6_11A_04_2"  "P6_11A_04_3"  "P6_11A_04_4"  "P6_11_05"
[306] "P6_11A_05_1"  "P6_11A_05_2"  "P6_11A_05_3"  "P6_11A_05_4"  "P6_11_06"
[311] "P6_11A_06_1"  "P6_11A_06_2"  "P6_11A_06_3"  "P6_11A_06_4"  "P6_11_07"
[316] "P6_11A_07_1"  "P6_11A_07_2"  "P6_11A_07_3"  "P6_11A_07_4"  "P6_11_08"
[321] "P6_11A_08_1"  "P6_11A_08_2"  "P6_11A_08_3"  "P6_11A_08_4"  "P6_11_09"
[326] "P6_11A_09_1"  "P6_11A_09_2"  "P6_11A_09_3"  "P6_11A_09_4"  "P6_11_10"
[331] "P6_11A_10_1"  "P6_11A_10_2"  "P6_11A_10_3"  "P6_11A_10_4"  "P6_11_11"
[336] "P6_11A_11_1"  "P6_11A_11_2"  "P6_11A_11_3"  "P6_11A_11_4"  "P6_11_12"
[341] "P6_11A_12_1"  "P6_11A_12_2"  "P6_11A_12_3"  "P6_11A_12_4"  "P6_11_13"
[346] "P6_11A_13_1"  "P6_11A_13_2"  "P6_11A_13_3"  "P6_11A_13_4"  "P6_11_14"
[351] "P6_11A_14_1"  "P6_11A_14_2"  "P6_11A_14_3"  "P6_11A_14_4"  "FILTRO_S6_12"
[356] "P6_12_01"     "P6_12A_01_1"  "P6_12A_01_2"  "P6_12A_01_3"  "P6_12A_01_4"
[361] "P6_12_02"     "P6_12A_02_1"  "P6_12A_02_2"  "P6_12A_02_3"  "P6_12A_02_4"
[366] "P6_12_03"     "P6_12A_03_1"  "P6_12A_03_2"  "P6_12A_03_3"  "P6_12A_03_4"
[371] "P6_12_04"     "P6_12A_04_1"  "P6_12A_04_2"  "P6_12A_04_3"  "P6_12A_04_4"
[376] "P6_12_05"     "P6_12A_05_1"  "P6_12A_05_2"  "P6_12A_05_3"  "P6_12A_05_4"
[381] "P6_12_06"     "P6_12A_06_1"  "P6_12A_06_2"  "P6_12A_06_3"  "P6_12A_06_4"
[386] "P6_12_07"     "P6_12A_07_1"  "P6_12A_07_2"  "P6_12A_07_3"  "P6_12A_07_4"
[391] "P6_12_08"     "P6_12A_08_1"  "P6_12A_08_2"  "P6_12A_08_3"  "P6_12A_08_4"
[396] "P6_12_09"     "P6_12A_09_1"  "P6_12A_09_2"  "P6_12A_09_3"  "P6_12A_09_4"
[401] "P6_12_10"     "P6_12A_10_1"  "P6_12A_10_2"  "P6_12A_10_3"  "P6_12A_10_4"
[406] "P6_12_11"     "P6_12A_11_1"  "P6_12A_11_2"  "P6_12A_11_3"  "P6_12A_11_4"
[411] "P6_12_12"     "P6_12A_12_1"  "P6_12A_12_2"  "P6_12A_12_3"  "P6_12A_12_4"
[416] "FILTRO_S6_13" "P6_13_1"      "P6_13A_1_1"   "P6_13A_1_2"   "P6_13A_1_3"
[421] "P6_13A_1_4"   "P6_13_2"      "P6_13A_2_1"   "P6_13A_2_2"   "P6_13A_2_3"
[426] "P6_13A_2_4"   "P6_13_3"      "P6_13A_3_1"   "P6_13A_3_2"   "P6_13A_3_3"
[431] "P6_13A_3_4"   "P6_13_4"      "P6_13A_4_1"   "P6_13A_4_2"   "P6_13A_4_3"
[436] "P6_13A_4_4"   "P6_13_5"      "P6_13A_5_1"   "P6_13A_5_2"   "P6_13A_5_3"
[441] "P6_13A_5_4"   "P6_13_6"      "P6_13A_6_1"   "P6_13A_6_2"   "P6_13A_6_3"
[446] "P6_13A_6_4"   "P6_13_7"      "P6_13A_7_1"   "P6_13A_7_2"   "P6_13A_7_3"
[451] "P6_13A_7_4"   "P6_13_8"      "P6_13A_8_1"   "P6_13A_8_2"   "P6_13A_8_3"
[456] "P6_13A_8_4"   "P6_13_9"      "P6_13A_9_1"   "P6_13A_9_2"   "P6_13A_9_3"
[461] "P6_13A_9_4"   "FILTRO_S6_14" "P6_14_1"      "P6_14A_1_1"   "P6_14A_1_2"
[466] "P6_14A_1_3"   "P6_14A_1_4"   "P6_14_2"      "P6_14A_2_1"   "P6_14A_2_2"
[471] "P6_14A_2_3"   "P6_14A_2_4"   "P6_14_3"      "P6_14A_3_1"   "P6_14A_3_2"
[476] "P6_14A_3_3"   "P6_14A_3_4"   "P6_14_4"      "P6_14A_4_1"   "P6_14A_4_2"
[481] "P6_14A_4_3"   "P6_14A_4_4"   "P6_14_5"      "P6_14A_5_1"   "P6_14A_5_2"
[486] "P6_14A_5_3"   "P6_14A_5_4"   "P6_14_6"      "P6_14A_6_1"   "P6_14A_6_2"
[491] "P6_14A_6_3"   "P6_14A_6_4"   "FILTRO_S6_15" "P6_15_1"      "P6_15A_1_1"
[496] "P6_15A_1_2"   "P6_15A_1_3"   "P6_15A_1_4"   "P6_15_2"      "P6_15A_2_1"
[501] "P6_15A_2_2"   "P6_15A_2_3"   "P6_15A_2_4"   "P6_15_3"      "P6_15A_3_1"
[506] "P6_15A_3_2"   "P6_15A_3_3"   "P6_15A_3_4"   "P6_15_4"      "P6_15A_4_1"
[511] "P6_15A_4_2"   "P6_15A_4_3"   "P6_15A_4_4"   "P6_15_5"      "P6_15A_5_1"
[516] "P6_15A_5_2"   "P6_15A_5_3"   "P6_15A_5_4"   "P6_15_6"      "P6_15A_6_1"
[521] "P6_15A_6_2"   "P6_15A_6_3"   "P6_15A_6_4"   "P6_15_7"      "P6_15A_7_1"
[526] "P6_15A_7_2"   "P6_15A_7_3"   "P6_15A_7_4"   "P6_16_1"      "P6_16A_1_1"
[531] "P6_16A_1_2"   "P6_16A_1_3"   "P6_16A_1_4"   "P6_16_2"      "P6_16A_2_1"
[536] "P6_16A_2_2"   "P6_16A_2_3"   "P6_16A_2_4"   "P6_16_3"      "P6_16A_3_1"
[541] "P6_16A_3_2"   "P6_16A_3_3"   "P6_16A_3_4"   "P6_16_4"      "P6_16A_4_1"
[546] "P6_16A_4_2"   "P6_16A_4_3"   "P6_16A_4_4"   "P6_16_5"      "P6_16A_5_1"
[551] "P6_16A_5_2"   "P6_16A_5_3"   "P6_16A_5_4"   "P6_16_6"      "P6_16A_6_1"
[556] "P6_16A_6_2"   "P6_16A_6_3"   "P6_16A_6_4"   "P6_17_1"      "P6_17A_1_1"
[561] "P6_17A_1_2"   "P6_17A_1_3"   "P6_17A_1_4"   "P6_17_2"      "P6_17A_2_1"
[566] "P6_17A_2_2"   "P6_17A_2_3"   "P6_17A_2_4"   "P6_17_3"      "P6_17A_3_1"
[571] "P6_17A_3_2"   "P6_17A_3_3"   "P6_17A_3_4"   "P6_18"        "P6_18A_1"
[576] "P6_18A_2"     "P6_18A_3"     "P6_18A_4"     "P6_19_1"      "P6_19A_1_1"
[581] "P6_19A_1_2"   "P6_19A_1_3"   "P6_19A_1_4"   "P6_19_2"      "P6_19A_2_1"
[586] "P6_19A_2_2"   "P6_19A_2_3"   "P6_19A_2_4"   "P6_20_1"      "P6_20A_1_1"
[591] "P6_20A_1_2"   "P6_20A_1_3"   "P6_20A_1_4"   "P6_20_2"      "P6_20A_2_1"
[596] "P6_20A_2_2"   "P6_20A_2_3"   "P6_20A_2_4"   "P6_21_1"      "P6_21A_1_1"
[601] "P6_21A_1_2"   "P6_21A_1_3"   "P6_21A_1_4"   "P6_21_2"      "P6_21A_2_1"
[606] "P6_21A_2_2"   "P6_21A_2_3"   "P6_21A_2_4"   "P6_21_3"      "P6_21A_3_1"
[611] "P6_21A_3_2"   "P6_21A_3_3"   "P6_21A_3_4"   "P6_21_4"      "P6_21A_4_1"
[616] "P6_21A_4_2"   "P6_21A_4_3"   "P6_21A_4_4"   "P6_22_1"      "P6_22A_1_1"
[621] "P6_22A_1_2"   "P6_22A_1_3"   "P6_22A_1_4"   "P6_22_2"      "P6_22A_2_1"
[626] "P6_22A_2_2"   "P6_22A_2_3"   "P6_22A_2_4"   "P6_22_3"      "P6_22A_3_1"
[631] "P6_22A_3_2"   "P6_22A_3_3"   "P6_22A_3_4"   "P6_22_4"      "P6_22A_4_1"
[636] "P6_22A_4_2"   "P6_22A_4_3"   "P6_22A_4_4"   "P6_22_5"      "P6_22A_5_1"
[641] "P6_22A_5_2"   "P6_22A_5_3"   "P6_22A_5_4"   "P6_22_6"      "P6_22A_6_1"
[646] "P6_22A_6_2"   "P6_22A_6_3"   "P6_22A_6_4"   "P6_23_1"      "P6_23A_1_1"
[651] "P6_23A_1_2"   "P6_23A_1_3"   "P6_23A_1_4"   "P6_23_2"      "P6_23A_2_1"
[656] "P6_23A_2_2"   "P6_23A_2_3"   "P6_23A_2_4"   "P6_23_3"      "P6_23_3C"
[661] "P6_23A_3_1"   "P6_23A_3_2"   "P6_23A_3_3"   "P6_23A_3_4"   "P7_1_1"
[666] "P7_1_2"       "P7_1_3"       "P7_1_4"       "P7_1_5"       "P7_1_6"
[671] "P7_1_7"       "P7_1_8"       "P7_2_01"      "P7_2_02"      "P7_2_03"
[676] "P7_2_04"      "P7_2_05"      "P7_2_06"      "P7_2_07"      "P7_2_08"
[681] "P7_2_09"      "P7_2_10"      "P7_2_11"      "CVEGEO"       "CVE_ENT"
[686] "TLOC"         "MENOR10"      "EST_DIS"      "UPM_DIS"      "FAC_PER"
[691] "CONTROL"      "VIV_SEL"      "HOGAR"        "N_REN"

In [10]:
datos <- datos %>%
  select(CVE_ENT, SEXO, P6_18, P6_18A_1, P6_18A_2, P6_18A_3, P6_18A_4, EDAD_V, EST_DIS, UPM_DIS, FAC_PER) %>%
  clean_names() %>%
  mutate(across(c(p6_18a_1, p6_18a_2, p6_18a_3, p6_18a_4), as.numeric)) %>%
  mutate(
    sexo = case_when(
      sexo == 1 ~ "Hombre",
      sexo == 2 ~ "Mujer",
      TRUE ~ "No especificado"
    ),
    deporte = case_when(
      p6_18 == 1 ~ "Sí",
      p6_18 == 2 ~ "No",
      TRUE ~ "No especificado"
    ),
    tiempo_total_semanal = (p6_18a_1 + (p6_18a_2 / 60) + p6_18a_3 + (p6_18a_4 / 60)),
    edad = case_when(
      edad_v >= 12 & edad_v <= 29 ~ "Personas jóvenes (12-29)",
      edad_v > 29 & edad_v <= 64 ~ "29-64",
      edad_v >= 65 ~ "Adultos mayores",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(as.character(cve_ent) %in% c("9", "09"))

head(datos)

  cve_ent sexo   p6_18 p6_18a_1 p6_18a_2 p6_18a_3 p6_18a_4 edad_v est_dis
1 09      Hombre 1      2       30        0        0       67     0073
2 09      Mujer  2     NA       NA       NA       NA       65     0073
3 09      Mujer  2     NA       NA       NA       NA       43     0073
4 09      Hombre 1      5        0        0        0       26     0073
5 09      Hombre 2     NA       NA       NA       NA       46     0073
6 09      Mujer  2     NA       NA       NA       NA       42     0073
  upm_dis fac_per deporte tiempo_total_semanal edad
1 01148   3165    Sí      2.5                  Adultos mayores
2 01148   3166    No       NA                  Adultos mayores
3 01148   3143    No       NA                  29-64
4 01148   3218    Sí      5.0                  Personas jóvenes (12-29)
5 01148   3209    No       NA                  29-64
6 01148   3143    No       NA                  29-64

In [11]:
# Diseño muestral 
dm <- datos %>%
  as_survey_design(
    ids = upm_dis,
    strata = est_dis,
    weights = fac_per,
    nest = TRUE
  )

In [12]:
cat("Total de la población de 12 años y más en la CDMX que respondieron de forma afirmativa
que durante la semana pasada, en su tiempo libre hicieron deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)\n")

deporte <- dm %>%
  group_by(deporte) %>%
  summarise(
    porcentaje_poblacion = survey_prop(vartype = "cv"),
    total_poblacion_n = survey_total(vartype = "cv")) %>%
  mutate(
    porcentaje_poblacion = round(porcentaje_poblacion * 100, 2)
  )
deporte

Total de la población de 12 años y más en la CDMX que respondieron de forma afirmativa
que durante la semana pasada, en su tiempo libre hicieron deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)

  deporte porcentaje_poblacion porcentaje_poblacion_cv total_poblacion_n
1 No      61.8                 0.02356880              5160156
2 Sí      38.2                 0.03812662              3189863
  total_poblacion_n_cv
1 0.03377544
2 0.04430037

In [13]:
cat("Distribución por sexo de la población de 12 años y más en la CDMX que respondieron de forma afirmativa
que durante la semana pasada, en su tiempo libre hicieron deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)\n")

deporte_sexo <- dm %>%
filter(deporte == "Sí") %>%
  group_by(deporte, sexo) %>%
  summarise(
    porcentaje_poblacion = survey_prop(vartype = "cv"),
    total_poblacion_n = survey_total(vartype = "cv")) %>%
  mutate(
    porcentaje_poblacion = round(porcentaje_poblacion * 100, 2)
  )
deporte_sexo

Distribución por sexo de la población de 12 años y más en la CDMX que respondieron de forma afirmativa
que durante la semana pasada, en su tiempo libre hicieron deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)

  deporte sexo   porcentaje_poblacion porcentaje_poblacion_cv total_poblacion_n
1 Sí      Hombre 51.43                0.02874693              1640464
2 Sí      Mujer  48.57                0.03043651              1549399
  total_poblacion_n_cv
1 0.05241877
2 0.05415260

In [14]:
cat("Horas promedio a la semana que la población de 12 años y más en la CDMX dedicó en su tiempo libre a hacer deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)\n")
tiempo_prom_deporte <- dm %>%
    filter(deporte == "Sí") %>%
  group_by(sexo) %>%
  summarise(
    horas_promedio_semana_deporte = survey_mean(tiempo_total_semanal, vartype = "cv", na.rm = TRUE)
  )%>%
  mutate(horas_promedio_semana_deporte = round(horas_promedio_semana_deporte, 2))
tiempo_prom_deporte

Horas promedio a la semana que la población de 12 años y más en la CDMX dedicó en su tiempo libre a hacer deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)

  sexo   horas_promedio_semana_deporte horas_promedio_semana_deporte_cv
1 Hombre 5.81                          0.04507897
2 Mujer  4.93                          0.04229621

In [15]:
cat("Horas promedio a la semana que la población de 12 años y más en la CDMX dedicó en su tiempo libre a hacer deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)\n")
tiempo_prom_deporte <- dm %>%
    filter(deporte == "Sí") %>%
  group_by(sexo, edad) %>%
  summarise(
    horas_promedio_semana_deporte = survey_mean(tiempo_total_semanal, vartype = "cv", na.rm = TRUE)
  )%>%
  mutate(horas_promedio_semana_deporte = round(horas_promedio_semana_deporte, 2))
tiempo_prom_deporte

Horas promedio a la semana que la población de 12 años y más en la CDMX dedicó en su tiempo libre a hacer deporte o ejercicio físico
(fútbol, basquetbol, natación, box, karate, caminar, correr, patinar,
andar en bicicleta, yoga, zumba)

  sexo   edad                     horas_promedio_semana_deporte
1 Hombre 29-64                    5.03
2 Hombre Adultos mayores          4.97
3 Hombre Personas jóvenes (12-29) 7.15
4 Mujer  29-64                    4.85
5 Mujer  Adultos mayores          3.86
6 Mujer  Personas jóvenes (12-29) 5.71
  horas_promedio_semana_deporte_cv
1 0.06293699
2 0.10335107
3 0.06762643
4 0.05623622
5 0.09523209
6 0.06358969